using Day22.Model;

namespace Day22.Reports
{
    public class SalesReport
    {
        private readonly List<SaleLineItem> _sales;
        private readonly List<Promotion> _promotions;

        public SalesReport(List<SaleLineItem> sales, List<Promotion> promotions)
        {
            _sales = sales;
            _promotions = promotions;
        }

        /// <summary>
        /// Returns the top N products based on total quantity sold.
        /// </summary>
        public IEnumerable<dynamic> TopSellingProducts(int topN)
        {
            if (topN <= 0)
                return Enumerable.Empty<dynamic>();

            return _sales
                .GroupBy(s => s.ProductName)
                .Select(g => new
                {
                    ProductName = g.Key,
                    TotalQuantity = g.Sum(s => s.Quantity)
                })
                .OrderByDescending(x => x.TotalQuantity)
                .Take(topN);
        }

        /// <summary>
        /// Returns total revenue generated by each category.
        /// Uses LINQ query syntax and a query continuation with into.
        /// </summary>
        public IEnumerable<dynamic> RevenueByCategory()
        {
            var query =
                from sale in _sales
                group sale by sale.Category into categoryGroup
                let Revenue = categoryGroup.Sum(s => s.LineTotal)
                orderby Revenue descending
                select new
                {
                    Category = categoryGroup.Key,
                    Revenue = Revenue
                };

            return query;
        }

        /// <summary>
        /// Returns staff performance including sales count, total revenue
        /// and average sale value, sorted by revenue and then staff name.
        /// </summary>
        public IEnumerable<dynamic> StaffPerformanceReport()
        {
            return _sales
                .GroupBy(s => s.StaffName)
                .Select(g => new
                {
                    StaffName = g.Key,
                    TotalSalesCount = g.Count(),
                    TotalRevenue = g.Sum(s => s.LineTotal),
                    AverageSaleValue = g.Average(s => s.LineTotal)
                })
                .OrderByDescending(x => x.TotalRevenue)
                .ThenBy(x => x.StaffName);
        }

        /// <summary>
        /// Returns sales grouped by the hour of the day,
        /// showing sale count and revenue for each hour.
        /// </summary>
        public IEnumerable<dynamic> HourlySalesTrend()
        {
            var query =
                from sale in _sales
                group sale by sale.SoldAt.Hour into hourlyGroup
                orderby hourlyGroup.Key
                select new
                {
                    Hour = hourlyGroup.Key,
                    SaleCount = hourlyGroup.Count(),
                    Revenue = hourlyGroup.Sum(s => s.LineTotal)
                };

            return query;
        }

        /// <summary>
        /// Returns percent-off promotions whose percentage is greater
        /// than the supplied minimum percentage.
        /// </summary>
        public IEnumerable<PercentOffPromotion> PercentOffPromotionsOver(double minPercent)
        {
            return _promotions
                .OfType<PercentOffPromotion>()
                .Where(p => p.PercentOff > minPercent)
                .OrderBy(p => p.PercentOff);
        }

        /// <summary>
        /// Returns categories whose total revenue is below the supplied threshold.
        /// Uses query continuation with group, into and where.
        /// </summary>
        public IEnumerable<dynamic> LowPerformingCategories(decimal revenueThreshold)
        {
            var query =
                from sale in _sales
                group sale by sale.Category into categoryGroup
                let Revenue = categoryGroup.Sum(s => s.LineTotal)
                where Revenue < revenueThreshold
                orderby Revenue
                select new
                {
                    Category = categoryGroup.Key,
                    Revenue = Revenue
                };

            return query;
        }

        /// <summary>
        /// Returns revenue, item count and highest-revenue category
        /// for every store location.
        /// </summary>
        public IEnumerable<dynamic> StoreComparisonReport()
        {
            return _sales
                .GroupBy(s => s.StoreLocation)
                .Select(storeGroup =>
                {
                    var categoryRevenue = storeGroup
                        .GroupBy(s => s.Category)
                        .Select(categoryGroup => new
                        {
                            Category = categoryGroup.Key,
                            Revenue = categoryGroup.Sum(s => s.LineTotal)
                        })
                        .OrderByDescending(x => x.Revenue)
                        .FirstOrDefault();

                    return new
                    {
                        StoreLocation = storeGroup.Key,
                        Revenue = storeGroup.Sum(s => s.LineTotal),
                        ItemCount = storeGroup.Sum(s => s.Quantity),
                        TopCategory = categoryRevenue?.Category ?? "No Sales",
                        TopCategoryRevenue = categoryRevenue?.Revenue ?? 0
                    };
                })
                .OrderByDescending(x => x.Revenue);
        }

        /// <summary>
        /// Demonstrates deferred execution by comparing a live query
        /// with a materialized snapshot after the source list is changed.
        /// </summary>
        public void DeferredVsSnapshotDemo()
        {
            Console.WriteLine("\n--- Deferred vs Snapshot Demo ---");

            var deferredQuery = _sales
                .Where(s => s.Category == "Electronics");

            var snapshot = _sales
                .Where(s => s.Category == "Electronics")
                .ToList();

            Console.WriteLine($"Electronics before mutation - Deferred: {deferredQuery.Count()}");
            Console.WriteLine($"Electronics before mutation - Snapshot: {snapshot.Count}");

            _sales.Add(new SaleLineItem
            {
                Id = 41,
                ProductName = "Smart Watch",
                Category = "Electronics",
                UnitPrice = 5000,
                Quantity = 2,
                StaffName = "Amit",
                StoreLocation = "Delhi",
                SoldAt = new DateTime(2026, 8, 22, 20, 0, 0)
            });

            Console.WriteLine("\nAdded a new Electronics sale.");

            Console.WriteLine($"Electronics after mutation - Deferred: {deferredQuery.Count()}");
            Console.WriteLine($"Electronics after mutation - Snapshot: {snapshot.Count}");

            Console.WriteLine(
                "\nExplanation: Deferred query executes when enumerated, " +
                "so it sees the new item. The snapshot was materialized " +
                "using ToList(), so it does not change."
            );
        }

        /// <summary>
        /// Provides an intentionally broken sorting example using two OrderBy calls.
        /// The second OrderBy replaces the first ordering.
        /// </summary>
        public IEnumerable<dynamic> BrokenStaffSort()
        {
            return _sales
                .GroupBy(s => s.StaffName)
                .Select(g => new
                {
                    StaffName = g.Key,
                    TotalRevenue = g.Sum(s => s.LineTotal)
                })
                .OrderByDescending(x => x.TotalRevenue)
                .OrderBy(x => x.StaffName);
        }

        /// <summary>
        /// Implements RevenueByCategory using method syntax instead of query syntax.
        /// Used for the syntax-equivalence check.
        /// </summary>
        public IEnumerable<dynamic> RevenueByCategoryMethodSyntax()
        {
            return _sales
                .GroupBy(s => s.Category)
                .Select(g => new
                {
                    Category = g.Key,
                    Revenue = g.Sum(s => s.LineTotal)
                })
                .OrderByDescending(x => x.Revenue);
        }

        /// <summary>
        /// Compares the query-syntax and method-syntax versions of RevenueByCategory.
        /// </summary>
        public void SyntaxEquivalenceCheck()
        {
            var queryVersion = RevenueByCategory().ToList();
            var methodVersion = RevenueByCategoryMethodSyntax().ToList();

            bool identical =
                queryVersion.Count == methodVersion.Count &&
                queryVersion.Zip(methodVersion)
                    .All(x =>
                        x.First.Category == x.Second.Category &&
                        x.First.Revenue == x.Second.Revenue);

            Console.WriteLine("\n--- Syntax Equivalence Check ---");

            if (identical)
                Console.WriteLine("PASS: Query syntax and method syntax produce identical results.");
            else
                Console.WriteLine("FAIL: Results are different.");
        }
    }
}